// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Comparison(arg1) {
  return window['go']['main']['App']['Comparison'](arg1);
}

export function DelComparisonResult() {
  return window['go']['main']['App']['DelComparisonResult']();
}

export function GetComparisonResult() {
  return window['go']['main']['App']['GetComparisonResult']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}
