// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Comparison(arg1:main.requestData):Promise<string>;

export function DelComparisonResult():Promise<string>;

export function GetComparisonResult(arg1:number,arg2:number):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;
